# Generated by Django 4.1.1 on 2022-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=20)),
                ('stocks', models.JSONField(default=[])),
            ],
        ),
    ]
