# Generated by Django 4.1.1 on 2022-09-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20220929_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='stocks',
            field=models.JSONField(default=[]),
        ),
    ]
