# Generated by Django 4.1.1 on 2022-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_remove_transaction_owner_remove_wallet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='stocks',
            field=models.JSONField(default=[]),
        ),
    ]
